UtilityLibrary::MessageUtilities
int UtilityLibrary.MessageUtilities.defColumn
Referenced by UtilityLibrary.MessageUtilities.fmtMsg< T >.
int UtilityLibrary.MessageUtilities.output
Referenced by UtilityLibrary.MessageUtilities.sendMsg.
RichTextBox UtilityLibrary.MessageUtilities.rtb
Referenced by UtilityLibrary.MessageUtilities.sendMsg.
string UtilityLibrary.MessageUtilities.nl
Referenced by UtilityLibrary.MessageUtilities.logMsgFmtln< T >, UtilityLibrary.MessageUtilities.logMsgln< T >.
static void UtilityLibrary.MessageUtilities.clearConsole()
static string UtilityLibrary.MessageUtilities.fmtInt(int i)
Referenced by UtilityLibrary.MessageUtilities.fmt< T >.
static string UtilityLibrary.MessageUtilities.fmt< T >(T var)
References UtilityLibrary.MessageUtilities.fmtInt.
static void UtilityLibrary.MessageUtilities.logMsgFmtln(string msg1)
static void UtilityLibrary.MessageUtilities.logMsgFmtln< T >(string msg1, T var1, int column=0, int shift=0)
References UtilityLibrary.MessageUtilities.logMsgFmt, UtilityLibrary.MessageUtilities.nl.
static void UtilityLibrary.MessageUtilities.logMsgFmt(string msg1)
Referenced by UtilityLibrary.MessageUtilities.logMsgFmtln< T >.
static void UtilityLibrary.MessageUtilities.logMsgFmt< T >(string msg1, T var1, int column=0, int shift=0)
static void UtilityLibrary.MessageUtilities.logMsgFmt< T >(string msg1, T var1, Color color, Font font, int column=0, int shift=0)
static string UtilityLibrary.MessageUtilities.fmtMsg< T >(string msg1, T var1, int column=0, int shift=0)
References UtilityLibrary.MessageUtilities.defColumn.
static void UtilityLibrary.MessageUtilities.logMsgln< T1, T2 >(T1 var1, T2 var2)
static void UtilityLibrary.MessageUtilities.logMsgln< T >(T var)
References UtilityLibrary.MessageUtilities.nl, UtilityLibrary.MessageUtilities.sendMsg.
static void UtilityLibrary.MessageUtilities.logMsg< T1, T2 >(T1 var1, T2 var2)
static void UtilityLibrary.MessageUtilities.logMsg< T >(T var)
References UtilityLibrary.MessageUtilities.sendMsg.
static void UtilityLibrary.MessageUtilities.logMsg< T >(T var, Color color, Font font)
References UtilityLibrary.MessageUtilities.sendMsg.
static void UtilityLibrary.MessageUtilities.sendMsg(string msg, Color color=new Color(), Font font=null)
References UtilityLibrary.MessageUtilities.output, UtilityLibrary.MessageUtilities.rtb.
Referenced by UtilityLibrary.MessageUtilities.logMsg< T >, UtilityLibrary.MessageUtilities.logMsgln< T >.
static string [] UtilityLibrary.MessageUtilities.splitPath(string fileAndPath)