AOTools::FormMeasurePoints
bool AOTools.FormMeasurePoints.showWorkplane
Referenced by AOTools.FormMeasurePoints.cbxWpOnOff_CheckedChanged.
bool AOTools.FormMeasurePoints.ShowWorkplane
Referenced by AOTools.FormMeasurePoints.LoadSettings, AOTools.DxMeasure.ShowHideWorkplane.
System.ComponentModel.IContainer AOTools.FormMeasurePoints.components
Required designer variable.
Referenced by AOTools.FormMeasurePoints.Dispose.
System.Windows.Forms.Button AOTools.FormMeasurePoints.btnDone
System.Windows.Forms.Button AOTools.FormMeasurePoints.btnSelect
System.Windows.Forms.Label AOTools.FormMeasurePoints.lblX1
System.Windows.Forms.Label AOTools.FormMeasurePoints.lblCoordinates
System.Windows.Forms.Label AOTools.FormMeasurePoints.lblPoint1
System.Windows.Forms.Label AOTools.FormMeasurePoints.lblY1
System.Windows.Forms.Label AOTools.FormMeasurePoints.lblZ1
System.Windows.Forms.Label AOTools.FormMeasurePoints.lblPoint2
System.Windows.Forms.Label AOTools.FormMeasurePoints.lblDistances
System.Windows.Forms.Label AOTools.FormMeasurePoints.lblAlongXaxis
System.Windows.Forms.Label AOTools.FormMeasurePoints.lblAlongYaxis
System.Windows.Forms.Label AOTools.FormMeasurePoints.lblAlongZaxis
System.Windows.Forms.Label AOTools.FormMeasurePoints.lblAlongXYaxis
System.Windows.Forms.Label AOTools.FormMeasurePoints.lblAlongYZaxis
System.Windows.Forms.Label AOTools.FormMeasurePoints.lblAlongXYZaxis
System.Windows.Forms.Label AOTools.FormMeasurePoints.lblAlongXZaxis
System.Windows.Forms.Label AOTools.FormMeasurePoints.lblNote
System.Windows.Forms.Label AOTools.FormMeasurePoints.lblWorkPlane
System.Windows.Forms.Label AOTools.FormMeasurePoints.lblZ2
System.Windows.Forms.Label AOTools.FormMeasurePoints.lblY2
System.Windows.Forms.Label AOTools.FormMeasurePoints.lblX2
System.Windows.Forms.CheckBox AOTools.FormMeasurePoints.cbxWpOnOff
System.Windows.Forms.Label AOTools.FormMeasurePoints.lblP1Z
System.Windows.Forms.Label AOTools.FormMeasurePoints.lblP1Y
System.Windows.Forms.Label AOTools.FormMeasurePoints.lblP1X
System.Windows.Forms.Label AOTools.FormMeasurePoints.lblP2Z
System.Windows.Forms.Label AOTools.FormMeasurePoints.lblP2Y
System.Windows.Forms.Label AOTools.FormMeasurePoints.lblP2X
System.Windows.Forms.Label AOTools.FormMeasurePoints.lblDistX
System.Windows.Forms.Label AOTools.FormMeasurePoints.lblDistY
System.Windows.Forms.Label AOTools.FormMeasurePoints.lblDistZ
System.Windows.Forms.Label AOTools.FormMeasurePoints.lblDistXY
System.Windows.Forms.Label AOTools.FormMeasurePoints.lblDistYZ
System.Windows.Forms.Label AOTools.FormMeasurePoints.lblDistXYZ
System.Windows.Forms.Label AOTools.FormMeasurePoints.lblDistXZ
System.Windows.Forms.Label AOTools.FormMeasurePoints.lblWpOrigin
System.Windows.Forms.Label AOTools.FormMeasurePoints.lblMessage
System.Windows.Forms.Label AOTools.FormMeasurePoints.lblWpNormal
System.Windows.Forms.Label AOTools.FormMeasurePoints.lblWpNormalZ
System.Windows.Forms.Label AOTools.FormMeasurePoints.lblWpNormalY
System.Windows.Forms.Label AOTools.FormMeasurePoints.lblWpNormalX
System.Windows.Forms.Label AOTools.FormMeasurePoints.lblWpOriginZ
System.Windows.Forms.Label AOTools.FormMeasurePoints.lblWpOriginY
System.Windows.Forms.Label AOTools.FormMeasurePoints.lblWpOriginX
AOTools.FormMeasurePoints.FormMeasurePoints()
References AOTools.FormMeasurePoints.InitializeComponent, AOTools.FormMeasurePoints.LoadSettings.
void AOTools.FormMeasurePoints.FormQueryPoints_FormClosing(object sender, FormClosingEventArgs e)
void AOTools.FormMeasurePoints.FormQueryPoints_Load(object sender, EventArgs e)
References AOTools.FormMeasurePoints.LoadSettings.
void AOTools.FormMeasurePoints.LoadSettings()
References AOTools.FormMeasurePoints.ShowWorkplane.
Referenced by AOTools.FormMeasurePoints.FormMeasurePoints, AOTools.FormMeasurePoints.FormQueryPoints_Load.
void AOTools.FormMeasurePoints.cbxWpOnOff_CheckedChanged(object sender, EventArgs e)
References AOTools.FormMeasurePoints.showWorkplane.
void AOTools.FormMeasurePoints.InitializeComponent()
Required method for Designer support - do not modify the contents of this method with the code editor.
Referenced by AOTools.FormMeasurePoints.FormMeasurePoints.
void AOTools.FormMeasurePoints.UpdatePoints(PointMeasurements?pm, Util.VType vtype, XYZ normal, XYZ origin, string planeName, Units units)
References AOTools.FormMeasurePoints.ClearText, AOTools.PointMeasurements.delta, AOTools.PointMeasurements.distanceXY, AOTools.PointMeasurements.distanceXYZ, AOTools.PointMeasurements.distanceXZ, AOTools.PointMeasurements.distanceYZ, AOTools.PointMeasurements.P1, AOTools.PointMeasurements.P2.
void AOTools.FormMeasurePoints.ClearText()
Referenced by AOTools.FormMeasurePoints.UpdatePoints.
override void AOTools.FormMeasurePoints.Dispose(bool disposing)
Clean up any resources being used.
disposing true if managed resources should be disposed; otherwise, false.
References AOTools.FormMeasurePoints.components.