AOTools::ExtensibleStorageMgr
FmtOpt
const string AOTools.ExtensibleStorageMgr.KEY_FMT_STR
bool AOTools.ExtensibleStorageMgr.initalized
Referenced by AOTools.ExtensibleStorageMgr.Init, AOTools.ExtensibleStorageMgr.SaveRevitBasicSettings.
readonly Dictionary<SBasicKey, FieldInfo> AOTools.ExtensibleStorageMgr._schemaFields
Referenced by AOTools.ExtensibleStorageMgr.Init.
readonly FieldInfo AOTools.ExtensibleStorageMgr._subSchemaFieldInfo
Referenced by AOTools.ExtensibleStorageMgr.ReadRevitUnitStyles.
readonly Dictionary<SUnitKey, FieldInfo> AOTools.ExtensibleStorageMgr._unitSchemaFields
Referenced by AOTools.ExtensibleStorageMgr.InitUnitSchema.
const string AOTools.ExtensibleStorageMgr.SCHEMA_NAME
Referenced by AOTools.ExtensibleStorageMgr.SaveRevitSettings.
const string AOTools.ExtensibleStorageMgr.SCHEMA_DESC
Referenced by AOTools.ExtensibleStorageMgr.SaveRevitSettings.
const string AOTools.ExtensibleStorageMgr.UNIT_SCHEMA_NAME
Referenced by AOTools.ExtensibleStorageMgr.MakeUnitSchema.
const string AOTools.ExtensibleStorageMgr.UNIT_SCHEMA_DESC
Referenced by AOTools.ExtensibleStorageMgr.MakeUnitSchema.
readonly Guid AOTools.ExtensibleStorageMgr.SchemaGUID
Referenced by AOTools.ExtensibleStorageMgr.DeleteCurrentSchema, AOTools.ExtensibleStorageMgr.ReadRevitBasicSettings, AOTools.ExtensibleStorageMgr.SaveRevitSettings.
Dictionary<SBasicKey, FieldInfo> AOTools.ExtensibleStorageMgr.SchemaFields
Referenced by AOTools.ExtensibleStorageMgr.Init, AOTools.ExtensibleStorageMgr.ListFieldInfo, AOTools.ExtensibleStorageMgr.ReadRevitBasicSettings, AOTools.ExtensibleStorageMgr.ReadRevitUnitStyles, AOTools.ExtensibleStorageMgr.SaveRevitSettings.
Dictionary<SUnitKey, FieldInfo> [] AOTools.ExtensibleStorageMgr.UnitSchemaFields
Referenced by AOTools.ExtensibleStorageMgr.InitUnitSchema, AOTools.ExtensibleStorageMgr.ListFieldInfo, AOTools.ExtensibleStorageMgr.ReadRevitSettings< T >, AOTools.ExtensibleStorageMgr.ReadRevitUnitStyles, AOTools.ExtensibleStorageMgr.SaveRevitSettings.
static void AOTools.ExtensibleStorageMgr.Init()
References AOTools.ExtensibleStorageMgr._schemaFields, AOTools.ExtensibleStorageMgr.initalized, AOTools.ExtensibleStorageMgr.InitUnitSchema, AOTools.ExtensibleStorageMgr.SchemaFields.
Referenced by AOTools.ExtensibleStorageMgr.ReadRevitBasicSettings.
static bool AOTools.ExtensibleStorageMgr.SaveRevitSettings()
References AOTools.ExtensibleStorageMgr.MakeUnitSchema, AOTools.ExtensibleStorageMgr.SCHEMA_DESC, AOTools.ExtensibleStorageMgr.SCHEMA_NAME, AOTools.ExtensibleStorageMgr.SchemaFields, AOTools.ExtensibleStorageMgr.SchemaGUID, AOTools.ExtensibleStorageMgr.UnitSchemaFields.
Referenced by AOTools.ExtensibleStorageMgr.SaveRevitBasicSettings.
static void AOTools.ExtensibleStorageMgr.MakeFields< T >(SchemaBuilder sbld, Dictionary< T, FieldInfo > fieldList)
general routine to make one schema field foreach item in a field info list
sbld fieldList
References AOTools.ExtensibleStorageMgr.MakeField.
static void AOTools.ExtensibleStorageMgr.MakeField(SchemaBuilder sbld, FieldInfo fieldInfo)
general routine to make a single schema field
sbld fieldInfo
References AOTools.ExtensibleStorageMgr.FieldInfo.UnitType.
Referenced by AOTools.ExtensibleStorageMgr.MakeFields< T >.
static Entity AOTools.ExtensibleStorageMgr.MakeUnitSchema(string guid, Dictionary< SUnitKey, FieldInfo > unitSchemaFields)
routine to make a unit schema and its fields
guid unitSchemaFields SchemaBuilder
References AOTools.ExtensibleStorageMgr.UNIT_SCHEMA_DESC, AOTools.ExtensibleStorageMgr.UNIT_SCHEMA_NAME.
Referenced by AOTools.ExtensibleStorageMgr.SaveRevitSettings.
static void AOTools.ExtensibleStorageMgr.SaveFieldValues< T >(Schema schema, Entity entity, Dictionary< T, FieldInfo > fieldList)
static bool AOTools.ExtensibleStorageMgr.ReadRevitSettings< T >(Dictionary< T, FieldInfo > fieldList, Guid guid)
References AOTools.ExtensibleStorageMgr.GetFieldValue, AOTools.ExtensibleStorageMgr.ReadRevitUnitStyles, AOTools.ExtensibleStorageMgr.UnitSchemaFields.
static bool AOTools.ExtensibleStorageMgr.ReadRevitUnitStyles(Entity elemEntity, Schema schema, Dictionary< SUnitKey, FieldInfo >[] unitSchemaFields)
References AOTools.ExtensibleStorageMgr._subSchemaFieldInfo, AOTools.ExtensibleStorageMgr.ReadSubEntity, AOTools.ExtensibleStorageMgr.SchemaFields, AOTools.ExtensibleStorageMgr.UnitSchemaFields.
Referenced by AOTools.ExtensibleStorageMgr.ReadRevitSettings< T >.
static dynamic AOTools.ExtensibleStorageMgr.GetFieldValue(Entity elemEntity, Schema schema, FieldInfo fi)
Referenced by AOTools.ExtensibleStorageMgr.ReadRevitSettings< T >.
static void AOTools.ExtensibleStorageMgr.ReadSubEntity(Entity subSchema, Schema schema, Dictionary< SUnitKey, FieldInfo > unitSchemaField)
Referenced by AOTools.ExtensibleStorageMgr.ReadRevitUnitStyles.
static void AOTools.ExtensibleStorageMgr.ListFieldInfo< T >(Dictionary< T, FieldInfo > fieldList)
static void AOTools.ExtensibleStorageMgr.DeleteCurrentSchema()
References AOTools.ExtensibleStorageMgr.SchemaGUID.
static void AOTools.ExtensibleStorageMgr.InitUnitSchema(int count)
References AOTools.ExtensibleStorageMgr._unitSchemaFields, AOTools.ExtensibleStorageMgr.UnitSchemaFields.
Referenced by AOTools.ExtensibleStorageMgr.Init.
static bool AOTools.ExtensibleStorageMgr.SaveRevitBasicSettings()
References AOTools.ExtensibleStorageMgr.initalized, AOTools.ExtensibleStorageMgr.SaveRevitSettings.
Referenced by AOTools.ExtensibleStorageMgr.ReadRevitBasicSettings.
static bool AOTools.ExtensibleStorageMgr.ReadRevitBasicSettings()
References AOTools.ExtensibleStorageMgr.Init, AOTools.ExtensibleStorageMgr.SaveRevitBasicSettings, AOTools.ExtensibleStorageMgr.SchemaFields, AOTools.ExtensibleStorageMgr.SchemaGUID.
static void AOTools.ExtensibleStorageMgr.ListFieldInfo()
References AOTools.ExtensibleStorageMgr.SchemaFields, AOTools.ExtensibleStorageMgr.UnitSchemaFields.