AOTools::AppRibbon
const string AOTools.AppRibbon.APP_NAME
Referenced by AOTools.Util.ReadManifest.
const string AOTools.AppRibbon.NAMESPACE_PREFIX
Referenced by AOTools.AppRibbon.AddPushButton.
const string AOTools.AppRibbon.BUTTON_NAME
Referenced by AOTools.AppRibbon.OnStartup.
const string AOTools.AppRibbon.PANEL_NAME
Referenced by AOTools.AppRibbon.OnStartup.
const string AOTools.AppRibbon.TAB_NAME
Referenced by AOTools.AppRibbon.OnStartup.
bool AOTools.AppRibbon._eventsRegistered
Referenced by AOTools.AppRibbon.RegisterDocEvents.
bool AOTools.AppRibbon._unitsConfigured
Referenced by AOTools.AppRibbon.ReadUnits.
UIControlledApplication AOTools.AppRibbon._uiCtrlApp
Referenced by AOTools.AppRibbon.OnStartup.
UIApplication AOTools.AppRibbon.UiApp
Referenced by AOTools.AppRibbon.OnIdling.
UIDocument AOTools.AppRibbon.Uidoc
Referenced by AOTools.AppRibbon.OnIdling.
Application AOTools.AppRibbon.App
Referenced by AOTools.AppRibbon.OnIdling.
Document AOTools.AppRibbon.Doc
Referenced by AOTools.AppRibbon.DocCreateEvent, AOTools.AppRibbon.DocOpenEvent, AOTools.AppRibbon.ReadUnits.
Result AOTools.AppRibbon.OnStartup(UIControlledApplication app)
References AOTools.AppRibbon._uiCtrlApp, AOTools.AppRibbon.AddPushButton, AOTools.AppRibbon.BUTTON_NAME, AOTools.AppRibbon.OnIdling, AOTools.AppRibbon.PANEL_NAME, AOTools.AppRibbon.TAB_NAME.
Result AOTools.AppRibbon.OnShutdown(UIControlledApplication a)
bool AOTools.AppRibbon.AddPushButton(RibbonPanel Panel, string ButtonName, string ButtonText, string Image16, string Image32, string dllPath, string dllClass, string ToolTip)
References AOTools.AppRibbon.NAMESPACE_PREFIX.
Referenced by AOTools.AppRibbon.OnStartup.
void AOTools.AppRibbon.AppClosing(object sender, ApplicationClosingEventArgs args)
References AOTools.AppRibbon.DocCreateEvent, AOTools.AppRibbon.DocOpenEvent.
Referenced by AOTools.AppRibbon.RegisterDocEvents.
void AOTools.AppRibbon.OnIdling(object sender, IdlingEventArgs e)
References AOTools.AppRibbon.App, AOTools.AppRibbon.RegisterDocEvents, AOTools.AppRibbon.UiApp, AOTools.AppRibbon.Uidoc.
Referenced by AOTools.AppRibbon.OnStartup.
bool AOTools.AppRibbon.RegisterDocEvents()
References AOTools.AppRibbon._eventsRegistered, AOTools.AppRibbon.AppClosing, AOTools.AppRibbon.DocCreateEvent, AOTools.AppRibbon.DocOpenEvent.
Referenced by AOTools.AppRibbon.OnIdling.
void AOTools.AppRibbon.DocOpenEvent(object sender, DocumentOpenedEventArgs args)
References AOTools.AppRibbon.Doc, AOTools.AppRibbon.ReadUnits.
Referenced by AOTools.AppRibbon.AppClosing, AOTools.AppRibbon.RegisterDocEvents.
void AOTools.AppRibbon.DocCreateEvent(object sender, DocumentCreatedEventArgs args)
References AOTools.AppRibbon.Doc, AOTools.AppRibbon.ReadUnits.
Referenced by AOTools.AppRibbon.AppClosing, AOTools.AppRibbon.RegisterDocEvents.
bool AOTools.AppRibbon.ReadUnits()
References AOTools.AppRibbon._unitsConfigured, AOTools.AppRibbon.Doc.
Referenced by AOTools.AppRibbon.DocCreateEvent, AOTools.AppRibbon.DocOpenEvent.