AOTools::ToggleRefPlane
Result AOTools.ToggleRefPlane.Execute(ExternalCommandData commandData, ref string message, ElementSet elements)
References AOTools.ToggleRefPlane.SetStatusText.
static int AOTools.ToggleRefPlane.SetWindowText(IntPtr hWnd, string lpString)
Referenced by AOTools.ToggleRefPlane.SetStatusText.
static IntPtr AOTools.ToggleRefPlane.FindWindowEx(IntPtr hwndParent, IntPtr hwndChildAfter, string lpszClass, string lpszWindow)
Referenced by AOTools.ToggleRefPlane.SetStatusText.
static void AOTools.ToggleRefPlane.SetStatusText(string text)
References AOTools.ToggleRefPlane.FindWindowEx, AOTools.ToggleRefPlane.GetWinHandle, AOTools.ToggleRefPlane.SetWindowText.
Referenced by AOTools.ToggleRefPlane.Execute.
static IntPtr AOTools.ToggleRefPlane.GetWinHandle()
Referenced by AOTools.ToggleRefPlane.SetStatusText.