AOTools::DxMeasure
FormMeasurePoints AOTools.DxMeasure._form
Referenced by AOTools.DxMeasure.Process, AOTools.DxMeasure.ShowHideWorkplane.
UIDocument AOTools.DxMeasure._uiDoc
Referenced by AOTools.DxMeasure.Execute, AOTools.DxMeasure.Process.
Document AOTools.DxMeasure._doc
Referenced by AOTools.DxMeasure.Execute, AOTools.DxMeasure.Process, AOTools.DxMeasure.ShowHideWorkplane.
Result AOTools.DxMeasure.Execute(ExternalCommandData commandData, ref string message, ElementSet elements)
References AOTools.DxMeasure._doc, AOTools.DxMeasure._uiDoc, AOTools.DxMeasure.Process.
static bool AOTools.DxMeasure.Process(UIDocument uiDoc, Document doc)
References AOTools.DxMeasure._doc, AOTools.DxMeasure._form, AOTools.DxMeasure._uiDoc, AOTools.DxMeasure.MeasurePts.
Referenced by AOTools.DxMeasure.Execute.
static bool AOTools.DxMeasure.MeasurePts(View av, VType vtype)
References AOTools.DxMeasure.GetPts, AOTools.DxMeasure.ShowHideWorkplane.
Referenced by AOTools.DxMeasure.Process.
static PointMeasurements AOTools.DxMeasure.GetPts(XYZ workingOrigin)
Referenced by AOTools.DxMeasure.MeasurePts.
static void AOTools.DxMeasure.ShowHideWorkplane(Plane p, View av)
References AOTools.DxMeasure._doc, AOTools.DxMeasure._form, AOTools.FormMeasurePoints.ShowWorkplane.
Referenced by AOTools.DxMeasure.MeasurePts.