//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AOToolsDelux.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AOToolsDelux.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create the {0} button.
        /// </summary>
        internal static string ButtonCreateFail {
            get {
                return ResourceManager.GetString("ButtonCreateFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decimal Feet Project Unit.
        /// </summary>
        internal static string R_ButtonStyleDecFeetName {
            get {
                return ResourceManager.GetString("R_ButtonStyleDecFeetName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decimal Inches Project Unit.
        /// </summary>
        internal static string R_ButtonStyleDecInchName {
            get {
                return ResourceManager.GetString("R_ButtonStyleDecInchName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fractional Inch Project Unit.
        /// </summary>
        internal static string R_ButtonStyleFracInName {
            get {
                return ResourceManager.GetString("R_ButtonStyleFracInName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feet &amp; Inch Project Unit.
        /// </summary>
        internal static string R_ButtonStyleFtInName {
            get {
                return ResourceManager.GetString("R_ButtonStyleFtInName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit Styles.
        /// </summary>
        internal static string UnitStyleButtonText {
            get {
                return ResourceManager.GetString("UnitStyleButtonText", resourceCulture);
            }
        }
    }
}
